[phases.setup]
nixPkgs = ['python311', 'nodejs', 'chromium']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'python -m playwright install-deps',
    'python -m playwright install chromium'
]

[phases.build]
cmds = ['echo "Build phase completed"']

[start]
cmd = 'gunicorn --config gunicorn.conf.py app:app'